// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5gY9VXJEL52P2SdU4ZgbqB8Y-k0YQuF4',
    appId: '1:779066729365:web:4c25ef9ff6d2defe078c9c',
    messagingSenderId: '779066729365',
    projectId: 'petshop-backend-9eec8',
    authDomain: 'petshop-backend-9eec8.firebaseapp.com',
    storageBucket: 'petshop-backend-9eec8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKCpmIcC_Hr3BE635EQkrcSkH44uETAY',
    appId: '1:779066729365:android:061e705b313218fb078c9c',
    messagingSenderId: '779066729365',
    projectId: 'petshop-backend-9eec8',
    storageBucket: 'petshop-backend-9eec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4tvUmnC7magUecdhy9UKsKqQfdgurzqM',
    appId: '1:779066729365:ios:a2741adfe93574e8078c9c',
    messagingSenderId: '779066729365',
    projectId: 'petshop-backend-9eec8',
    storageBucket: 'petshop-backend-9eec8.appspot.com',
    iosClientId: '779066729365-3thn9drfps01lpv2s5qc81qb3065logs.apps.googleusercontent.com',
    iosBundleId: 'com.example.petshopFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4tvUmnC7magUecdhy9UKsKqQfdgurzqM',
    appId: '1:779066729365:ios:a2741adfe93574e8078c9c',
    messagingSenderId: '779066729365',
    projectId: 'petshop-backend-9eec8',
    storageBucket: 'petshop-backend-9eec8.appspot.com',
    iosClientId: '779066729365-3thn9drfps01lpv2s5qc81qb3065logs.apps.googleusercontent.com',
    iosBundleId: 'com.example.petshopFront',
  );
}
